/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package simrskhanza;

/**
 *
 * @author perpustakaan
 */
public class DlgAbout extends javax.swing.JDialog {

    
    public DlgAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(10,10);
        setSize(465,515);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        jLabel6 = new javax.swing.JLabel();
        panelGlass1 = new usu.widget.glass.PanelGlass();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelGlass4 = new usu.widget.glass.PanelGlass();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        panelGlass5 = new usu.widget.glass.PanelGlass();
        panelGlass7 = new usu.widget.glass.PanelGlass();
        panelGlass8 = new usu.widget.glass.PanelGlass();
        panelGlass9 = new usu.widget.glass.PanelGlass();
        panelGlass10 = new usu.widget.glass.PanelGlass();
        panelGlass11 = new usu.widget.glass.PanelGlass();
        panelGlass12 = new usu.widget.glass.PanelGlass();
        panelGlass13 = new usu.widget.glass.PanelGlass();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        panelGlass2 = new usu.widget.glass.PanelGlass();
        BtnKeluar = new widget.Button();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelGlass14 = new usu.widget.glass.PanelGlass();
        panelGlass15 = new usu.widget.glass.PanelGlass();
        panelGlass16 = new usu.widget.glass.PanelGlass();
        panelGlass17 = new usu.widget.glass.PanelGlass();
        panelGlass18 = new usu.widget.glass.PanelGlass();
        panelGlass19 = new usu.widget.glass.PanelGlass();
        panelGlass20 = new usu.widget.glass.PanelGlass();
        panelGlass21 = new usu.widget.glass.PanelGlass();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("::[ About Program ]::");
        setUndecorated(true);
        setResizable(false);

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "::[ About Program ]::", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(50, 50, 50));
        jLabel6.setText(".: Detail  Update SIMRS Khanza Naray Hospital");
        jLabel6.setName("jLabel6"); // NOI18N
        internalFrame1.add(jLabel6);
        jLabel6.setBounds(500, 30, 360, 20);

        panelGlass1.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        panelGlass1.setOpaqueImage(false);
        panelGlass1.setRound(false);
        panelGlass1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(50, 50, 50));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Database Server :");
        jLabel4.setName("jLabel4"); // NOI18N
        panelGlass1.add(jLabel4);
        jLabel4.setBounds(0, 22, 104, 14);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(50, 50, 50));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Versi Aplikasi :");
        jLabel7.setName("jLabel7"); // NOI18N
        panelGlass1.add(jLabel7);
        jLabel7.setBounds(0, 8, 104, 14);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(50, 50, 50));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Default Database :");
        jLabel8.setName("jLabel8"); // NOI18N
        panelGlass1.add(jLabel8);
        jLabel8.setBounds(0, 36, 104, 14);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(50, 50, 50));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("File Konfigurasi :");
        jLabel9.setName("jLabel9"); // NOI18N
        panelGlass1.add(jLabel9);
        jLabel9.setBounds(0, 50, 104, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(50, 50, 50));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Default Port :");
        jLabel10.setName("jLabel10"); // NOI18N
        panelGlass1.add(jLabel10);
        jLabel10.setBounds(0, 64, 104, 14);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(50, 50, 50));
        jLabel11.setText("Untuk mensetting aplikasi menjadi Client");
        jLabel11.setName("jLabel11"); // NOI18N
        panelGlass1.add(jLabel11);
        jLabel11.setBounds(230, 8, 210, 14);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(50, 50, 50));
        jLabel12.setText("Server, ganti HOST Localhost dengan");
        jLabel12.setName("jLabel12"); // NOI18N
        panelGlass1.add(jLabel12);
        jLabel12.setBounds(230, 22, 200, 14);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(50, 50, 50));
        jLabel13.setText("alamat/IP Address dari server yang di");
        jLabel13.setName("jLabel13"); // NOI18N
        panelGlass1.add(jLabel13);
        jLabel13.setBounds(230, 36, 200, 14);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(50, 50, 50));
        jLabel14.setText("gunakan. Jagan lupa untuk mengatur hak");
        jLabel14.setName("jLabel14"); // NOI18N
        panelGlass1.add(jLabel14);
        jLabel14.setBounds(230, 50, 220, 14);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(50, 50, 50));
        jLabel17.setText("Update 2025-04-15");
        jLabel17.setName("jLabel17"); // NOI18N
        panelGlass1.add(jLabel17);
        jLabel17.setBounds(107, 8, 120, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(50, 50, 50));
        jLabel5.setText("MySQL Server");
        jLabel5.setName("jLabel5"); // NOI18N
        panelGlass1.add(jLabel5);
        jLabel5.setBounds(107, 22, 120, 14);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(50, 50, 50));
        jLabel18.setText("sik");
        jLabel18.setName("jLabel18"); // NOI18N
        panelGlass1.add(jLabel18);
        jLabel18.setBounds(107, 36, 120, 14);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(50, 50, 50));
        jLabel29.setText("database.xml");
        jLabel29.setName("jLabel29"); // NOI18N
        panelGlass1.add(jLabel29);
        jLabel29.setBounds(107, 50, 120, 14);

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(50, 50, 50));
        jLabel30.setText("3306");
        jLabel30.setName("jLabel30"); // NOI18N
        panelGlass1.add(jLabel30);
        jLabel30.setBounds(107, 64, 120, 14);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(50, 50, 50));
        jLabel38.setText("akses di MySQL server agar terkoneksi");
        jLabel38.setName("jLabel38"); // NOI18N
        panelGlass1.add(jLabel38);
        jLabel38.setBounds(230, 70, 210, 14);

        internalFrame1.add(panelGlass1);
        panelGlass1.setBounds(10, 50, 454, 90);

        jLabel16.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(50, 50, 50));
        jLabel16.setText(".: Developer");
        jLabel16.setName("jLabel16"); // NOI18N
        internalFrame1.add(jLabel16);
        jLabel16.setBounds(10, 135, 110, 20);

        panelGlass4.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(241, 246, 236)));
        panelGlass4.setOpaqueImage(false);
        panelGlass4.setRound(false);
        panelGlass4.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(50, 50, 50));
        jLabel19.setText("RS Permata Medika Kebumen, RS Handayani Lampung Utara, ");
        jLabel19.setName("jLabel19"); // NOI18N
        panelGlass4.add(jLabel19);
        jLabel19.setBounds(126, 160, 320, 14);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(50, 50, 50));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Blog :");
        jLabel24.setName("jLabel24"); // NOI18N
        panelGlass4.add(jLabel24);
        jLabel24.setBounds(0, 30, 55, 14);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(50, 50, 50));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Phone :");
        jLabel20.setName("jLabel20"); // NOI18N
        panelGlass4.add(jLabel20);
        jLabel20.setBounds(0, 10, 55, 14);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(50, 50, 50));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Email :");
        jLabel21.setName("jLabel21"); // NOI18N
        panelGlass4.add(jLabel21);
        jLabel21.setBounds(0, 50, 55, 14);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(50, 50, 50));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Github :");
        jLabel22.setName("jLabel22"); // NOI18N
        panelGlass4.add(jLabel22);
        jLabel22.setBounds(0, 70, 55, 14);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(50, 50, 50));
        jLabel23.setText("Kontributor & Donatur : RS Jeumpa Pontianak Kalimantan Barat, RS Sadewa Yogyakarta,");
        jLabel23.setName("jLabel23"); // NOI18N
        panelGlass4.add(jLabel23);
        jLabel23.setBounds(10, 100, 440, 14);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(50, 50, 50));
        jLabel25.setText("RS Puri Husada Sleman Yogyakarta, RS Pelita Insani Martapura,");
        jLabel25.setName("jLabel25"); // NOI18N
        panelGlass4.add(jLabel25);
        jLabel25.setBounds(126, 120, 320, 14);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(50, 50, 50));
        jLabel26.setText("RS Assyifa Manna, RS Arvita Bunda Sleman Yogyakarta,");
        jLabel26.setName("jLabel26"); // NOI18N
        panelGlass4.add(jLabel26);
        jLabel26.setBounds(126, 140, 320, 14);

        panelGlass5.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass5.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass5.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass5.setRound(false);
        panelGlass5.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass5.setLayout(null);

        panelGlass7.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass7.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass7.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass7.setRound(false);
        panelGlass7.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass7.setLayout(null);
        panelGlass5.add(panelGlass7);
        panelGlass7.setBounds(0, 280, 330, 70);

        panelGlass8.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass8.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass8.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass8.setRound(false);
        panelGlass8.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass8.setLayout(null);

        panelGlass9.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass9.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass9.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass9.setRound(false);
        panelGlass9.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass9.setLayout(null);
        panelGlass8.add(panelGlass9);
        panelGlass9.setBounds(0, 280, 330, 70);

        panelGlass5.add(panelGlass8);
        panelGlass8.setBounds(0, 280, 330, 70);

        panelGlass10.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass10.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass10.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass10.setRound(false);
        panelGlass10.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass10.setLayout(null);

        panelGlass11.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass11.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass11.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass11.setRound(false);
        panelGlass11.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass11.setLayout(null);
        panelGlass10.add(panelGlass11);
        panelGlass11.setBounds(0, 280, 330, 70);

        panelGlass12.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass12.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass12.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass12.setRound(false);
        panelGlass12.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass12.setLayout(null);

        panelGlass13.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass13.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass13.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass13.setRound(false);
        panelGlass13.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass13.setLayout(null);
        panelGlass12.add(panelGlass13);
        panelGlass13.setBounds(0, 280, 330, 70);

        panelGlass10.add(panelGlass12);
        panelGlass12.setBounds(0, 280, 330, 70);

        panelGlass5.add(panelGlass10);
        panelGlass10.setBounds(50, 280, 330, 70);

        panelGlass4.add(panelGlass5);
        panelGlass5.setBounds(60, 290, 330, 70);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(50, 50, 50));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Bagi yang ingin melakukan Donasi, bisa ke Rekening BSI 1015369872, kode bank 451");
        jLabel27.setName("jLabel27"); // NOI18N
        panelGlass4.add(jLabel27);
        jLabel27.setBounds(16, 240, 420, 14);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(50, 50, 50));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("atas nama Windiarto");
        jLabel28.setName("jLabel28"); // NOI18N
        panelGlass4.add(jLabel28);
        jLabel28.setBounds(16, 260, 420, 14);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(50, 50, 50));
        jLabel31.setText("08562675039     Pengembang : Windiarto Nugroho, Dewi Ekawati, YASKI dll");
        jLabel31.setName("jLabel31"); // NOI18N
        panelGlass4.add(jLabel31);
        jLabel31.setBounds(58, 10, 420, 14);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(50, 50, 50));
        jLabel32.setText("elkhanza.wordpress.com, simrskhanza.weebly.com, yaski.or.id");
        jLabel32.setName("jLabel32"); // NOI18N
        panelGlass4.add(jLabel32);
        jLabel32.setBounds(58, 30, 430, 14);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(50, 50, 50));
        jLabel33.setText("khanza_media@yahoo.com, khanzasoftmedia@gmail.com");
        jLabel33.setName("jLabel33"); // NOI18N
        panelGlass4.add(jLabel33);
        jLabel33.setBounds(58, 50, 420, 14);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(50, 50, 50));
        jLabel34.setText("github.com/mas-elkhanza     Instagram : simrskhanza");
        jLabel34.setName("jLabel34"); // NOI18N
        panelGlass4.add(jLabel34);
        jLabel34.setBounds(58, 70, 420, 14);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(50, 50, 50));
        jLabel35.setText("RS Haji Kamino Way Kanan, RS PKU Jatinom Klaten, RS Khalisah,");
        jLabel35.setName("jLabel35"); // NOI18N
        panelGlass4.add(jLabel35);
        jLabel35.setBounds(126, 180, 320, 14);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(50, 50, 50));
        jLabel36.setText("RS Alam Medica Bumiayu, dll");
        jLabel36.setName("jLabel36"); // NOI18N
        panelGlass4.add(jLabel36);
        jLabel36.setBounds(126, 200, 320, 14);

        internalFrame1.add(panelGlass4);
        panelGlass4.setBounds(7, 155, 454, 370);

        jLabel37.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(50, 50, 50));
        jLabel37.setText(".: Aplikasi ");
        jLabel37.setName("jLabel37"); // NOI18N
        internalFrame1.add(jLabel37);
        jLabel37.setBounds(10, 18, 90, 20);

        panelGlass2.setBackground(new java.awt.Color(235, 255, 235));
        panelGlass2.setBorder(new javax.swing.border.MatteBorder(null));
        panelGlass2.setOpaqueImage(false);
        panelGlass2.setRound(false);
        panelGlass2.setLayout(null);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Close");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setIconTextGap(3);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass2.add(BtnKeluar);
        BtnKeluar.setBounds(490, 440, 100, 30);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Update Juli : \n- Pembaruan Warna Tampilan\n- NIP Login & Tanggal Ditampilkan Diatas Kanan\n-  Pembaruan Tabel Rawat Jalan\n- Mempermudah user untuk mencetak SPRI\n- Pemberian warna pada tabel sesuai status\n- Perbaikan pada golongan darah di pendaftaran pasien\n\nNantikan Update selanjutnya dari Tim IT Naray Hospital.^_^\n\n-WT25-");
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        panelGlass2.add(jScrollPane1);
        jScrollPane1.setBounds(14, 10, 560, 210);

        panelGlass14.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass14.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/devopsengineer.png"))); // NOI18N
        panelGlass14.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass14.setRound(false);
        panelGlass14.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass14.setLayout(null);

        panelGlass15.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass15.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass15.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass15.setRound(false);
        panelGlass15.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass15.setLayout(null);
        panelGlass14.add(panelGlass15);
        panelGlass15.setBounds(0, 280, 330, 70);

        panelGlass16.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass16.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass16.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass16.setRound(false);
        panelGlass16.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass16.setLayout(null);

        panelGlass17.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass17.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass17.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass17.setRound(false);
        panelGlass17.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass17.setLayout(null);
        panelGlass16.add(panelGlass17);
        panelGlass17.setBounds(0, 280, 330, 70);

        panelGlass14.add(panelGlass16);
        panelGlass16.setBounds(0, 280, 330, 70);

        panelGlass18.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass18.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass18.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass18.setRound(false);
        panelGlass18.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass18.setLayout(null);

        panelGlass19.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass19.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass19.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass19.setRound(false);
        panelGlass19.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass19.setLayout(null);
        panelGlass18.add(panelGlass19);
        panelGlass19.setBounds(0, 280, 330, 70);

        panelGlass20.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass20.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass20.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass20.setRound(false);
        panelGlass20.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass20.setLayout(null);

        panelGlass21.setBackground(new java.awt.Color(254, 254, 254));
        panelGlass21.setBackgroundImage(new javax.swing.ImageIcon(getClass().getResource("/picture/khanza.png"))); // NOI18N
        panelGlass21.setBackgroundImageType(usu.widget.constan.BackgroundConstan.BACKGROUND_IMAGE_STRECT);
        panelGlass21.setRound(false);
        panelGlass21.setWarna(new java.awt.Color(235, 255, 235));
        panelGlass21.setLayout(null);
        panelGlass20.add(panelGlass21);
        panelGlass21.setBounds(0, 280, 330, 70);

        panelGlass18.add(panelGlass20);
        panelGlass20.setBounds(0, 280, 330, 70);

        panelGlass14.add(panelGlass18);
        panelGlass18.setBounds(50, 280, 330, 70);

        panelGlass2.add(panelGlass14);
        panelGlass14.setBounds(180, 230, 260, 220);

        internalFrame1.add(panelGlass2);
        panelGlass2.setBounds(500, 60, 590, 480);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);
        internalFrame1.getAccessibleContext().setAccessibleName("::[ Detail  ]::");
        internalFrame1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        dispose();
}//GEN-LAST:event_BtnKeluarKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgAbout dialog = new DlgAbout(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private usu.widget.glass.PanelGlass panelGlass1;
    private usu.widget.glass.PanelGlass panelGlass10;
    private usu.widget.glass.PanelGlass panelGlass11;
    private usu.widget.glass.PanelGlass panelGlass12;
    private usu.widget.glass.PanelGlass panelGlass13;
    private usu.widget.glass.PanelGlass panelGlass14;
    private usu.widget.glass.PanelGlass panelGlass15;
    private usu.widget.glass.PanelGlass panelGlass16;
    private usu.widget.glass.PanelGlass panelGlass17;
    private usu.widget.glass.PanelGlass panelGlass18;
    private usu.widget.glass.PanelGlass panelGlass19;
    private usu.widget.glass.PanelGlass panelGlass2;
    private usu.widget.glass.PanelGlass panelGlass20;
    private usu.widget.glass.PanelGlass panelGlass21;
    private usu.widget.glass.PanelGlass panelGlass4;
    private usu.widget.glass.PanelGlass panelGlass5;
    private usu.widget.glass.PanelGlass panelGlass7;
    private usu.widget.glass.PanelGlass panelGlass8;
    private usu.widget.glass.PanelGlass panelGlass9;
    // End of variables declaration//GEN-END:variables

}
